apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  backend
    spec:
      containers:
      - name:  backend
        image:  dmomotic/so2-backend:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: MONGODB_USERNAME
          value: sa
        - name: MONGODB_PASSWORD
          value: sa
        - name: MONGODB_URL
          value: sa.4d9ky.mongodb.net
        - name: MONGODB_NAME
          value: goals
        ports:
        - containerPort:  80
          name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - name: backend-service
    port: 80 
    targetPort: 80
    protocol: TCP